name: Build and Run Docker Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t noteapp:latest .

      - name: Run Docker container
        run: docker run -d --name noteapp_container -p 8080:8080 noteapp:latest

      - name: List running containers
        run: docker ps

      - name: Show container logs
        run: docker logs noteapp_container

      - name: Stop and remove container
        run: |
          docker stop noteapp_container
          docker rm noteapp_container